### ISSUE TITLE
npm start - multiple errors

### ISSUE THREAD

**Issue by MonsterGameDev** [joeeames/PSAngularUnitTestingCourse#2]
Im having troubles running the angular unit test project on multiple machines... Maybe you have a lot of global installs that i dont. My friend are having the excact same problem.
npm i runs without problems
npm start => Cannot find module 'webpack'
Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:547:15)

running npm i webpack i can move on but are stopped by:
ENOENT... cannot find jquery.min.js (in fact node_modules holds no jquery folder at all after npm i)
running npm i jquery  and then npm start brings me to
ENOENT ... cannot find toastr.min.js
another install and start later
ENOENT ... cannot find bootstrap.js
npm i bootstrap finally brings me to:
ERROR in multi ./node_modules/toastr/build/toastr.min.css ./node_modules/ngf-bootstrap/dist/bootstrap.min.css ./src/styles.css

so i give up...

I should mention that i have run dkuratas beginning ngrx and several other ng-courses on plural without any problems

Regards
Per Høyer

**Comment by joeeames** [comment]
First off don't run "npm start" 
That has nothing to do with this course. The application is never really run as part of this course.
"npm test" is the command that matters.

**Comment by joeeames** [comment]
Please let me know if this resolves your issue. 

Also, in the future, please use the discussion forum. That's what these types of questions are for, and it lets others with the same issue contribute to the discussion.

**Comment by MonsterGameDev** [comment]
Maaan that was a quick response.. thanks so much. im running the plural course, and you DO run npm start in mod 2 to se the "heros", that was why i tried :-) but... i shall follow your advice and run the npm test instead, but... project wont build

**Comment by joeeames** [comment]
k, that's totally my bad. I will be updating the code to work, but it's so unimportant to run it, I think I'll add in a note to NOT follow along, because it may be broken.

Honestly, it's faster response here (the discussion forum has a longer delay before they email me with notification) but I usually try to respond quick. I just like having this in the forum so others can see.

For example, this same issue was already reported by someone over there, so I told them the same thing, and I'm aware of the issue. I'll be working on it but it's just not a huge priority since having the code run doesn't really matter to the course.

**Comment by MonsterGameDev** [comment]
And yes i shall use the discussion forum on plural ... Thanks again for the quick response - npm test runs like a charm :-)

**Comment by joeeames** [comment]
OK. great to hear. thanks for your help. I'll change this readme as well to note that the code doesn't run at the moment.

**Comment by joeeames** [comment]
check out the readme/main page for this repo and let me know if you think that's helpful for now until I get the code fixed.

**Comment by MonsterGameDev** [comment]
u write: Do not try to run this code with "npm run"... shouldnt it be "npm start" (or ng serve)... except from that - its very helpful... :-)

**Comment by MonsterGameDev** [comment]
:-)

**Comment by joeeames** [comment]
I just pushed a new version up. Could you do me a favor and do a fresh clone, install, and then "npm start" and also "npm test" let me know if anything gives you a problem? It all works for me but I'd prefer more validation

**Comment by MonsterGameDev** [comment]
oh year sure, right away

**Comment by MonsterGameDev** [comment]
Everything works - it builds and shows up correctly in the browser... :-) so cool
And just love your definition of "not a huge priority..." what was it... 30 or 40 minutes :-)
Just finished watching mod 3 - its a pleasure watching :-) 
thanks again

**Comment by joeeames** [comment]
well, being honest, I was recording an episode of JavaScript Jabber, and I wasn't too involved, so I worked on it, and it turned out it wasn't too tough to get to and fix. So given a different situation it could have taken me days or weeks to get to. :)

Cheers, glad you're enjoying the course. If you have any q's (that aren't useful on the discussion) or other feedback, feel free to hit me up on twitter and DM me.

Enjoy

**Comment by joeeames** [comment]
Oh my goodness, TOTALLY forgot to thank you for validating the fix. REALLY appreciate that. gonna go update the readme now.

**Comment by MonsterGameDev** [comment]
tnx :-)
